ssh_opts:
    - '-oConnectTimeout=2'
    - '-oStrictHostKeyChecking=no'
    - '-oUserKnownHostsFile=/dev/null'
    - '-oLogLevel=error'
    - '-lroot'
    - '-oBatchMode=yes'
env_vars:
    - 'OPENRC=/root/openrc'
    - 'IPTABLES_STR="iptables -nvL"'
fuelip:  '127.0.0.1'
rqdir: './rq'
soft_filter:
    status:  ['ready']
timeout: 15
compress_timeout: 3600
logs:
    path: '/var/log'
    include: 'kern.log'
    exclude: '[-_]\d{8}$|atop[-_]|\.gz$'
# by_role:
#     compute:
#         logs:
#             path: '/var/log'
#             include: 'compute'
#     ceph-osd:
#         logs:
#             path: '/var/log'
#             include: 'ceph'
# by_node_id:
#     1:
#         env_vars:
#             - 'OPENRC=/root/openrc'
#             - 'IPTABLES_STR="iptables -S"'
#         logs:
#             path: '/var/log'
#             include: 'messages'
