ssh_opts:
    - -oConnectTimeout=2
    - -oStrictHostKeyChecking=no
    - -oUserKnownHostsFile=/dev/null
    - -oLogLevel=error
    - -lroot
    - -oBatchMode=yes
env_vars:
    - OPENRC=/root/openrc
    - IPTABLES_STR="iptables -nvL"
fuelip:  127.0.0.1
rqdir: ./rq
soft_filter:
    status:  ['ready']
timeout: 15
compress_timeout: 3600
log_files:
    path: /var/log
    filter:
        default:
            include: '(.)*'
            exclude: '[-_]\d{8}$|atop[-_]|\.gz$'

