ssh:
    opts: -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -lroot -oBatchMode=yes
    vars: OPENRC=/root/openrc IPTABLES_STR="iptables -nvL"
fuelip:  127.0.0.1
rqdir:   ./rq
soft_filter:
    status:  ['ready']
timeout: 15
log_files:
    path: /var/log
    filter:
        default:
            include: '(.)*'
            exclude: 'atop-|atop_'
        by_node_id:
             0:
                 include: '(.)*'
                 exclude: '^/var/log/remote/|^/var/log/docker\-logs/remote/'
