ssh:
    opts: -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -lroot -oBatchMode=yes
    vars: OPENRC=/root/openrc IPTABLES_STR="iptables -nvL"
fuelip:  127.0.0.1
rqdir:   ./rq
logdir:  ./logs
out-dir: ../timmy-ng/info
timeout: 15
find:
    template: -name '*.log'
log-files:
     default: -name '*.log'
     by-role:
         compute: -name '*.log'
         controller: -name '*.log' -name '*.log' -o -name '*.log.1' -o -name '*' ! -path '/var/log/atop*'
         mongo: -name '*.log'
         ceph: -name '*.log'
     by-node-id:
         0: -name '*.log' -o -name '*.log.1'
